mimir:
  structuredConfig:
    common:
      storage:
        backend: gcs
        gcs:
          bucket_name: lgtm-bucket # Create your storage bucket before deploying the chart.
    blocks_storage:
      backend: gcs
      storage_prefix: blocks
    alertmanager_storage:
      backend: gcs
      storage_prefix: alertmanager
    ruler_storage:
      backend: gcs
      storage_prefix: ruler
minio:
  enabled: false
ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false

