mimir:
  structuredConfig:
    common:
      storage:
        backend: gcs
        gcs:
          bucket_name: lgtm-bucket
    blocks_storage:
      backend: gcs
      storage_prefix: blocks
    alertmanager_storage:
      backend: gcs
      storage_prefix: alertmanager
    ruler_storage:
      backend: gcs
      storage_prefix: ruler
        #nginx:
        #  ingress:
        #    enabled: false
        #    ingressClassName: nginx
        #    hosts:
        #      - host: nginx.mimir.com
        #        paths:
        #          - path: /
        #            pathType: Prefix
        #    tls:
        #      - secretName: mimir-tls
        #        hosts:
        #          - nginx.mimir.com
minio:
  enabled: false
ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false

